#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := esp_startup
EXTRA_COMPONENT_DIRS += ./lib
CFLAGS += -DESP_DEV_MODULE -DPLATFORM_ESP8266

include $(IDF_PATH)/make/project.mk

