name: Build all projects

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Install Flawfinder
        run: pip install flawfinder
      - name: Build relays
        working-directory: projects/relays
        run: platformio run -e esp-dev
      - name: Build bmp280
        working-directory: projects/bmp280
        run: platformio run -e esp-dev
      - name: Build plantsitter
        working-directory: projects/plantsitter
        run: platformio run -e esp-dev