name: Test cli_helper_server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      working-directory: ${{github.workspace}}/cli_helper_server
      run: cmake -B build -GNinja

    - name: Compile
      working-directory: ${{github.workspace}}/cli_helper_server/build
      run: ninja

    - name: Run Tests
      run: ctest -V

