name: Create documentation

on: [push]

jobs:
  build-examples:
    name: Generate docs.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'false'
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Doxygen
        run: apt install doxygen -y
        shell: bash
      - name: Generate Doxygen Documentation
        working-directory: projects/lib_tests
        run: doxygen Doxyfile
        shell: bash