name: Create documentation

on: [push]

jobs:
  build-examples:
    name: Build for ${{ matrix.idf_target }} on ${{ matrix.idf_ver }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        idf_ver: ["release-v5.2", "latest"]
        idf_target: ["esp32"]
    container: espressif/idf:${{ matrix.idf_ver }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'false'
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Doxygen
        run: sudo apt-get install doxygen -y
        shell: bash
      - name: Generate Doxygen Documentation
        working-directory: projects/lib_tests
        run: doxygen Doxyfile
        shell: bash