name: Doxygenize esp_startup

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Doxygenize
        uses: langroodi/doxygenize@v1.7.0
        with:
          doxygenconf: 'esp_startup/Doxyfile'
