name: Build lib tests

on: [push]

jobs:
  build-examples:
    name: Build for ${{ matrix.idf_target }} on ${{ matrix.idf_ver }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        idf_ver: ["release-v5.2", "latest"]
        idf_target: ["esp32"]
    container: espressif/idf:${{ matrix.idf_ver }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'false'
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: esp-idf build
        env:
          IDF_TARGET: ${{ matrix.idf_target }}
        shell: bash
        working-directory: projects/lib_tests
        run: |
          ${IDF_PATH}/./install.sh --enable-pytest
          . ${IDF_PATH}/export.sh
          cp -Rf ../bmp280/lib/wifi_controller lib/
          ls -la lib
          python build_all.py
          pytest --embedded-services=qemu,idf -m qemu --junitxml "junit/test_reports"
      - name: Run pytest on qemu.
        working-directory: projects/lib_tests
        run: |
            pwd
            ls -la
            ls -la junit
            python -m pip install junit2html
            junit2html junit/test_reports
