name: Build lib tests

on: [push]

jobs:
  build-examples:
    name: Build for ${{ matrix.idf_target }} on ${{ matrix.idf_ver }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        idf_ver: ["release-v5.2", "latest"]
        idf_target: ["esp32"]
    container: espressif/idf:${{ matrix.idf_ver }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'false'
      - name: esp-idf build
        env:
          IDF_TARGET: ${{ matrix.idf_target }}
        shell: bash
        working-directory: projects/lib_tests
        run: |
          . ${IDF_PATH}/export.sh
          cp -Rf lib test_logger/
          cd test_logger
          mv lib components
          ls -la components
          ls -la
          pwd
          idf.py build
