name: Test qemu lib_tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: espressif/idf
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "esp_helper"
      - name: Install Docker
        uses: papodaca/install-docker-action@v1
      - name: Go to lib_tests.
        run: |
            cd esp_helper/projects/lib_tests/
      - name: esp-idf build tes_sys_utils
        run: docker run --rm -v $PWD:/test_sys_utils -w /test_sys_utils espressif/idf idf.py build
      - name: esp-idf build test_logger
        run: docker run --rm -v $PWD:/test_logger -w /test_logger espressif/idf idf.py build                     
      - name: Run pytest on qemu.
        run: |
            pytest --embedded-services=qemu,idf -m qemu --junitxml "junit/test_reports"
            pip install junit2html
            junit2html junit/test_reports
