name: Build lib tests

on: [push]

jobs:
  build-examples:
    name: Build for ${{ matrix.idf_target }} on ${{ matrix.idf_ver }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        idf_ver: ["release-v5.2", "latest"]
        idf_target: ["esp32"]
    container: espressif/idf:${{ matrix.idf_ver }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'false'
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
     # - name: doxygen-install
      #  uses: ssciwr/doxygen-install@v1.3.0
      - name: Doxygenize
  # You may pin to the exact commit or the version.
  # uses: langroodi/doxygenize@542946a13bc9021f5ba07c8751e6ab3d84bca154
        uses: langroodi/doxygenize@v1.7.0
        with:
          # Doxygen configuration file path
          doxygenconf: projects/lib_tests/Doxyfile
          # Generated HTML documents output folder
          htmloutput: projects/lib_tests/
          # Toggle dark mode CSS
          darkmode: true
      - name: esp-idf run qemu tests
        env:
          IDF_TARGET: ${{ matrix.idf_target }}
        shell: bash
        working-directory: projects/lib_tests
        run: |
          ${IDF_PATH}/./install.sh --enable-pytest
          . ${IDF_PATH}/export.sh
          python clean_all.py
          python build_all.py
          pytest --embedded-services=qemu,idf -m qemu --junitxml "junit/test_reports"
      - name: Run junit2html on test results
        working-directory: projects/lib_tests
        run: |
            python -m pip install junit2html
            junit2html junit/test_reports
      - name: Install PlatformIO Core
        run: python -m pip install --upgrade platformio
      - name: Install Flawfinder
        run: python -m pip install flawfinder
      - name: Run Platofrmio native tests
        working-directory: projects/lib_tests
        run: |
          platformio test --verbose --environment linux
