name: Test qemu lib_tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: espressif/idf
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "esp_helper"
      - name: Go to lib_tests.
        run: |
            cd esp_helper/projects/lib_tests/
      - name: esp-idf build tes_sys_utils
        uses: espressif/esp-idf-ci-action@v1
        with:
            esp_idf_version: v5.3
            target: esp32
            path: 'test_sys_utils'
      - name: esp-idf build logger
        uses: espressif/esp-idf-ci-action@v1
        with:
            esp_idf_version: v5.3
            target: esp32
            path: 'test_logger'          
      - name: Run pytest on qemu.
        run: |
            pytest --embedded-services=qemu,idf -m qemu --junitxml "junit/test_reports"
            pip install junit2html
            junit2html junit/test_reports
