name: Test qemu lib_tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install ESP-IDF prerequisites
        run: sudo apt-get install git wget flex bison gperf python3 python3-pip python3-venv cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0
      - name: Get ESP-IDF
        run: |
            mkdir -p ~/esp
            cd ~/esp
            git clone --recursive https://github.com/espressif/esp-idf.git
      - name: Set up the Tools for ESP-IDF
        run: |
            cd ~/esp/esp-idf
            ./install.sh esp32 --enable-pytest
            . $HOME/esp/esp-idf/export.sh
            pwd
            la
